logLevel: DEBUG
credentials:
  host: localhost
  port: 3306
  database: s142_stats
  username: root
  password: 1234
pool:
  sizing:
    initialSize: 10
    minIdle: 0
    maxSize: 10
  timeouts:
    maxAcquireTimeMillis: 10000
    maxCreateConnectionTimeMillis: 30000
    maxValidationTimeMillis: -1
    maxIdleTimeMillis: 60000
    maxLifeTimeMillis: 1800000
