name: surf-stats-paper
version: '${version}'
main: dev.slne.surf.stats.paper.SurfStatsPlugin
description: Player statistics management system for Surf servers
api-version: '1.21'
author: SLNE Dev Team

load: POSTWORLD
folia-supported: true

dependencies:
  server:
    surf-bukkit-api:
      load: BEFORE
      required: true
