import type { Metadata } from "next";
import { ThemeProvider } from "../components/theme/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<script
					src="https://kit.fontawesome.com/f630097af5.js"
					crossOrigin="anonymous"
					async
				></script>
			</head>
			<body className="font-mono text-lg">
				<ThemeProvider>
					<main className="min-h-screen">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
